apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-cluster-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-cluster-controller
    spec:
      serviceAccountName: strimzi-cluster-controller
      containers:
        - name: strimzi-cluster-controller
          image: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-clustercontroller-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
          env:
            - name: STRIMZI_CONFIGMAP_LABELS
              value: "strimzi.io/kind=cluster"
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
              value: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-zookeeper-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
            - name: STRIMZI_DEFAULT_KAFKA_IMAGE
              value: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-kafka-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
            - name: STRIMZI_DEFAULT_KAFKA_CONNECT_IMAGE
              value: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-kafkaconnect-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
            - name: STRIMZI_DEFAULT_KAFKA_CONNECT_S2I_IMAGE
              value: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-kafkaconnects2i-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
            - name: STRIMZI_DEFAULT_TOPIC_CONTROLLER_IMAGE
              value: registry.access.redhat.com/amqstreams1-dev-preview/amqstreams10-topiccontroller-openshift-0f88c08f84d63cec06e50826e5af7bdc:1.0
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
  strategy:
    type: Recreate
