apiVersion: v1
kind: ConfigMap
metadata:
  name: my-topic
  labels:
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: my-topic
  partitions: "3"
  replicas: "3"
  config: |-
    {
      "retention.bytes": "104857600",
      "retention.ms": "86400000",
      "segment.bytes": "10485760"
    }
